name: Deploy Worder Bot

on:
  workflow_dispatch: # Добавляет кнопку "Run workflow" в интерфейсе GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/devuser/worder
            git fetch --all
            git reset --hard origin/main

            # 1. Гарантируем наличие venv (если вдруг удалили)
            python3 -m venv venv

            # 2. Обновляем pip и устанавливаем зависимости
            ./venv/bin/python -m pip install --upgrade pip
            ./venv/bin/pip install -r requirements.txt

            # 3. Перезапускаем конкретный сервис
            sudo systemctl restart worder
